server:
  port: 9080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: postgres
    password: 1234567890
    url: jdbc:postgresql://localhost:5432/mybatis_example
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.jmalltech.pojo
  mapper-locations: classpath:mappers/*.xml

