server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis_example?currentSchema=mybatis_demo01
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.jmalltech.pojo
  mapper-locations: classpath:mappers/*.xml


